language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"
script:
  - npm run build
  - cp dist/index.html dist/404.html
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  repo: "vechain/insight"
  on:
    branch: master
